/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  STETHDepositHelper,
  STETHDepositHelperInterface,
} from "../STETHDepositHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_curveETHSTETHPool",
        type: "address",
      },
      {
        internalType: "address",
        name: "_stETHVault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_stETH",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "curveETHSTETHPool",
    outputs: [
      {
        internalType: "contract ICurveETHSTETHPool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minSTETHAmount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "stETH",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stETHVault",
    outputs: [
      {
        internalType: "contract IRibbonThetaVault",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class STETHDepositHelper__factory {
  static readonly abi = _abi;
  static createInterface(): STETHDepositHelperInterface {
    return new utils.Interface(_abi) as STETHDepositHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): STETHDepositHelper {
    return new Contract(address, _abi, signerOrProvider) as STETHDepositHelper;
  }
}
