#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd ./shared && yarn lint && cd ../webapp && yarn lint && cd ../landing && yarn lint && cd ../nft-drop && yarn lint && cd ../governance && yarn lint && cd ..
npx lint-staged
